name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==4.0.2
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==15.1.0
  - escapism==1.0.1
  - python-kubernetes
  - kubernetes_asyncio
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  # JHub Apps dependencies
  - flask
  - panel
  - bokeh
  - pip:
    - nebari-jupyterhub-theme
    - python-keycloak==0.26.1
    - git+https://github.com/nebari-dev/jhub-apps.git@3ae44a53e2c6f2caa5c74d9a64f03228cf9968dc
